export const CAMPOS_FORMATIVOS_POR_NIVEL: Record<string, Record<string, string[]>> = {
  "Preescolar": {
    "1": ["LENGUAJE", "SABERES PENSAMIENTO CIENTÍFICO", "ETICA NATURALEZA SOCIEDADES", "HUMANO Y COMUNITARIO"],
    "2": ["LENGUAJE", "SABERES PENSAMIENTO CIENTÍFICO", "ETICA NATURALEZA SOCIEDADES", "HUMANO Y COMUNITARIO"],
    "3": ["LENGUAJE", "SABERES PENSAMIENTO CIENTÍFICO", "ETICA NATURALEZA SOCIEDADES", "HUMANO Y COMUNITARIO"]
  },
  "Primaria": {
    "1": ["LENGUAJES", "SABERES Y PENSAMIENTO CIENTÍFICO", "ÉTICA, NATURALEZA Y SOCIEDADES", "DE LO HUMANO Y LO COMUNITARIO"],
    "2": ["LENGUAJES", "SABERES Y PENSAMIENTO CIENTÍFICO", "ÉTICA, NATURALEZA Y SOCIEDADES", "DE LO HUMANO Y LO COMUNITARIO"],
    "3": ["LENGUAJES", "SABERES Y PENSAMIENTO CIENTÍFICO", "ÉTICA, NATURALEZA Y SOCIEDADES", "DE LO HUMANO Y LO COMUNITARIO"],
    "4": ["LENGUAJES", "SABERES Y PENSAMIENTO CIENTÍFICO", "ÉTICA, NATURALEZA Y SOCIEDADES", "DE LO HUMANO Y LO COMUNITARIO"],
    "5": ["LENGUAJES", "SABERES Y PENSAMIENTO CIENTÍFICO", "ÉTICA, NATURALEZA Y SOCIEDADES", "DE LO HUMANO Y LO COMUNITARIO"],
    "6": ["LENGUAJES", "SABERES Y PENSAMIENTO CIENTÍFICO", "ÉTICA, NATURALEZA Y SOCIEDADES", "DE LO HUMANO Y LO COMUNITARIO"]
  },
  "Secundaria": {
    "1": ["ESPAÑOL", "INGLES", "ARTES", "MATEMATICAS", "BIOLOGIA", "GEOGRAFIA", "HISTORIA", "FORMACION CIVICA Y ETICA", "TECNOLOGIA", "TUTORIA", "EDUCACION FISICA"],
    "2": ["ESPAÑOL", "INGLES", "ARTES", "MATEMATICAS", "FISICA", "HISTORIA", "FORMACION CIVICA Y ETICA", "TECNOLOGIA", "TUTORIA", "EDUCACION FISICA"],
    "3": ["ESPAÑOL", "INGLES", "ARTES", "MATEMATICAS", "QUIMICA", "HISTORIA", "FORMACION CIVICA Y ETICA", "TECNOLOGIA", "TUTORIA", "EDUCACION FISICA"]
  }
};

export const ESTRATEGIAS_EVALUACION = [
  'Observación directa',
  'Lista de cotejo',
  'Rúbrica',
  'Portafolio de evidencias',
  'Proyecto final',
  'Examen escrito',
  'Examen oral',
  'Autoevaluación',
  'Coevaluación',
  'Diario de aprendizaje',
];
